import toMap from 'src/misc/toMap'

export default toMap([
  'RESOURCE',
  'RESOURCE_PROP_UPDATED',
  'RESOURCE_NEEDED',
  'RESOURCE_NOT_NEEDED',
  'RESOURCE_REQUESTED',
  'RESOURCE_DISPOSED',
  'RESOURCE_UPDATED_DEP',
  'RESOURCE_WATCHED',
  'RESOURCE_UNWATCHED', // TODO handle RESOURCE_UNWATCHED
  'RESOURCE_WATCHED_UPDATED',
])
